'use client';
import Link from 'next/link';
import { createContext, useContext, useEffect, useMemo, useState } from 'react';
import { Product, money } from './store-data';
import { api } from './api';
type CartLine = Product & {quantity:number};
type Store = {cart:CartLine[];add:(p:Product)=>void;change:(id:number,d:number)=>void;remove:(id:number)=>void;count:number;total:number;favorite:(id:number)=>void;favorites:number[];toast:string|null;dark:boolean;toggleDark:()=>void};
const StoreContext=createContext<Store|null>(null);
export const useStore=()=>{const value=useContext(StoreContext);if(!value)throw new Error('StoreProvider ausente');return value};
export function StoreProvider({children}:{children:React.ReactNode}){const [cart,setCart]=useState<CartLine[]>([]);const[favorites,setFavorites]=useState<number[]>([]);const[toast,setToast]=useState<string|null>(null);const[dark,setDark]=useState(false);const auth=()=>({Authorization:`Bearer ${localStorage.getItem('emarket-token')??''}`});useEffect(()=>{const c=localStorage.getItem('emarket-cart'),f=localStorage.getItem('emarket-favorites'),d=localStorage.getItem('emarket-dark');if(c)setCart(JSON.parse(c));if(f)setFavorites(JSON.parse(f));setDark(d==='true')},[]);useEffect(()=>localStorage.setItem('emarket-cart',JSON.stringify(cart)),[cart]);useEffect(()=>localStorage.setItem('emarket-favorites',JSON.stringify(favorites)),[favorites]);useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('emarket-dark',String(dark))},[dark]);const say=(m:string)=>{setToast(m);window.setTimeout(()=>setToast(null),2500)};const value=useMemo(()=>({cart,count:cart.reduce((s,x)=>s+x.quantity,0),total:cart.reduce((s,x)=>s+x.quantity*x.price,0),add:(p:Product)=>{setCart(c=>{const found=c.find(x=>x.id===p.id);return found?c.map(x=>x.id===p.id?{...x,quantity:x.quantity+1}:x):[...c,{...p,quantity:1}]});void api('/cart/items',{method:'POST',headers:auth(),body:JSON.stringify({productId:p.id,quantity:1})}).catch(()=>undefined);say(`${p.name} adicionado ao carrinho`)},change:(id:number,d:number)=>{setCart(c=>{const item=c.find(x=>x.id===id);if(item)void api(`/cart/items/${id}`,{method:'PATCH',headers:auth(),body:JSON.stringify({quantity:item.quantity+d})}).catch(()=>undefined);return c.flatMap(x=>x.id===id&&x.quantity+d<=0?[]:x.id===id?[{...x,quantity:x.quantity+d}]:[x])})},remove:(id:number)=>{setCart(c=>c.filter(x=>x.id!==id));void api(`/cart/items/${id}`,{method:'DELETE',headers:auth()}).catch(()=>undefined);say('Item removido do carrinho')},favorite:(id:number)=>setFavorites(f=>f.includes(id)?f.filter(x=>x!==id):[...f,id]),favorites,toast,dark,toggleDark:()=>setDark(x=>!x)}),[cart,favorites,toast,dark]);return <StoreContext.Provider value={value}>{children}{toast&&<div className="toast" role="status">OK · {toast}</div>}</StoreContext.Provider>}
export function Shell({children}:{children:React.ReactNode}){const{count,dark,toggleDark}=useStore();return <div className="page"><div className="topbar"><div className="container"><span>Entrega rápida para sua região</span><span>Seg a sáb · 08h às 21h</span></div></div><header className="header"><div className="container header-main"><Link className="logo" href="/"><span className="logo-mark">e</span><span>E-Market</span></Link><form className="search" action="/pesquisa"><input name="q" placeholder="Busque produtos, marcas e categorias" aria-label="Buscar produtos"/><span>⌕</span></form><div className="header-actions"><button className="icon-link" onClick={toggleDark} aria-label="Alternar tema">{dark?'☀':'◐'}</button><Link className="icon-link favs" href="/favoritos">♡</Link><Link className="icon-link account" href="/perfil">Conta</Link><Link className="cart-link" href="/carrinho">Carrinho{count?` (${count})`:''}</Link></div></div><nav className="nav"><div className="container"><Link href="/categorias">Categorias</Link><Link href="/ofertas">Ofertas</Link><Link href="/produtos/picanha-friboi-peca">Mais vendidos</Link><Link href="/categorias/hortifruti">Hortifruti</Link><Link href="/categorias/acougue">Açougue</Link><Link href="/pedidos">Meus pedidos</Link><Link href="/perfil">Minha conta</Link></div></nav></header>{children}<footer className="footer"><div className="container footer-grid"><div><Link className="logo" href="/"><span className="logo-mark">e</span><span>E-Market</span></Link><p>Seu mercado de confiança, agora a um toque de distância.</p></div><div><h4>Comprar</h4><Link href="/categorias">Categorias</Link><Link href="/ofertas">Ofertas do dia</Link><Link href="/favoritos">Favoritos</Link></div><div><h4>Atendimento</h4><a href="#">Central de ajuda</a><a href="#">Fale conosco</a></div><div><h4>Minha conta</h4><Link href="/login">Entrar</Link><Link href="/pedidos">Meus pedidos</Link><Link href="/perfil">Dados pessoais</Link></div></div><div className="container footer-end">© 2026 E-Market · Compras simples, frescas e seguras.</div></footer></div>}
export function SectionHeading({eyebrow,title,description}:{eyebrow?:string;title:string;description?:string}){return <div className="section-heading"><div>{eyebrow&&<p className="eyebrow" style={{color:'#17683a'}}>{eyebrow}</p>}<h2>{title}</h2>{description&&<p>{description}</p>}</div></div>}
export function ProductCard({product}:{product:Product}){const{add,favorite,favorites}=useStore();return <article className="product"><Link href={`/produtos/${product.slug}`}><div className="product-art" style={{'--product-bg':product.bg} as React.CSSProperties}>{product.image?<img src={product.image} alt={product.name} loading="lazy"/>:product.emoji}</div></Link>{product.tag&&<span className="product-tag">{product.tag}</span>}<button className={`heart ${favorites.includes(product.id)?'active':''}`} onClick={()=>favorite(product.id)} aria-label="Adicionar aos favoritos">♥</button><div className="product-info"><span className="unit">{product.brand?`${product.brand} · `:''}{product.unit}</span><Link href={`/produtos/${product.slug}`}><h3>{product.name}</h3></Link>{product.oldPrice&&<span className="old-price">{money(product.oldPrice)}</span>}<div className="buy-row"><span className="price">{money(product.price)}</span><button className="add" onClick={()=>add(product)} aria-label={`Adicionar ${product.name}`}>+</button></div></div></article>}
